import Head from 'next/head'
import Movie from '../../models/Movie';
import conectionDB from '../../lib/dbConnect';
import Link from 'next/link';

export default function Home({movies}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1 className="text-center text-uppercase my-3 bg-warning">Películas</h1>
        <Link href={'/new'}>
          <button className="btn btn-primary my-1 mb-3 w-100 ">Agregar película</button>
        </Link>
        {
          movies.map(({_id, title, description}) => (
            <div className="card mb-2" key={_id}>
              <div className="card-body">
                <div className="h5 text-uppercase">{title}</div>
                <p className="fw-light">{description}</p>
                <Link href={`/${_id}`}>
                  <button className="btn btn-success btn-sm">Ver película</button>
                </Link>
              </div>
            </div>
          ))
        }
      </main>
    </div>
  )
}


export const getServerSideProps = async () => {
  try {
    await conectionDB();

    const res = await Movie.find();
    
    const movies= res.map(mov => {
      const movie= mov.toObject();
      movie._id = `${movie._id}`;
      
      return movie;
    })

    return { props: { movies } };
  } catch (error) {
    console.log(error);
    return { props: {success: false, error: '¡Error!'} };
  }
};